"""add_jd_text_to_application

Revision ID: 5aa343565399
Revises: bb1ad7123b3c
Create Date: 2026-04-21 10:45:14.592884

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5aa343565399'
down_revision = 'bb1ad7123b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('jd_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'jd_text')
    # ### end Alembic commands ###
