/** Escape a string for safe insertion into a LaTeX document. */
export function latexEscape(str: string): string {
  return str
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
}

export interface LatexInput {
  fullName: string
  phone: string
  linkedinUrl: string
  githubUrl: string
  summary: string
  experiences: Array<{
    company: string
    role_title: string
    start_date: string
    end_date: string | null
    location: string
    bullets: string[]
  }>
  projects: Array<{
    name: string
    tech_stack: string
    bullets: string[]
    github_url?: string | null
  }>
  skills: {
    languages: string
    frameworks: string
    tools: string
  }
}

export function buildLatex(input: LatexInput): string {
  const e = latexEscape
  const { fullName, phone, linkedinUrl, githubUrl, summary, experiences, projects, skills } = input

  const experienceBlocks = experiences.map((exp) => {
    const dateRange = exp.end_date ? `${e(exp.start_date)} -- ${e(exp.end_date)}` : `${e(exp.start_date)} -- Present`
    const bulletLines = exp.bullets.map((b) => `      \\resumeItem{${e(b)}}`).join("\n")
    return `    \\resumeSubheading
      {${e(exp.company)}}{${dateRange}}
      {${e(exp.role_title)}}{${e(exp.location)}}
      \\resumeItemListStart
${bulletLines}
      \\resumeItemListEnd`
  }).join("\n\n")

  const projectBlocks = projects.map((proj) => {
    const techLine = `\\textbf{Technologies:} ${e(proj.tech_stack)}`
    const githubLine = proj.github_url ? ` \\textbar{} \\href{${proj.github_url}}{GitHub}` : ""
    const bulletLines = proj.bullets.map((b) => `      \\resumeItem{${e(b)}}`).join("\n")
    return `    \\resumeProjectHeading
      {\\textbf{${e(proj.name)}} $|$ ${techLine}${githubLine}}{}
      \\resumeItemListStart
${bulletLines}
      \\resumeItemListEnd`
  }).join("\n\n")

  const contactParts: string[] = []
  if (phone) contactParts.push(e(phone))
  if (linkedinUrl) contactParts.push(`\\href{${linkedinUrl}}{LinkedIn}`)
  if (githubUrl) contactParts.push(`\\href{${githubUrl}}{GitHub}`)

  return `%-------------------------
% Resume — auto-generated by Reed
%-------------------------
\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{\\vspace{-4pt}\\scshape\\raggedright\\large}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]
\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{\\item\\small{#1 \\vspace{-2pt}}}
\\newcommand{\\resumeSubheading}[4]{\\vspace{-2pt}\\item
  \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
    \\textbf{#1} & #2 \\\\
    \\textit{\\small#3} & \\textit{\\small #4} \\\\
  \\end{tabular*}\\vspace{-7pt}}
\\newcommand{\\resumeProjectHeading}[2]{\\item
  \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
    \\small#1 & #2 \\\\
  \\end{tabular*}\\vspace{-7pt}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}

\\begin{document}

%-----------HEADER-----------
\\begin{center}
  {\\Huge \\scshape ${e(fullName)}} \\\\ \\vspace{4pt}
  \\small ${contactParts.join(" $|$ ")}
\\end{center}

%-----------SUMMARY-----------
\\section{Summary}
${e(summary)}

%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
${experienceBlocks}
  \\resumeSubHeadingListEnd

%-----------PROJECTS-----------
\\section{Projects}
  \\resumeSubHeadingListStart
${projectBlocks}
  \\resumeSubHeadingListEnd

%-----------SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     \\textbf{Languages}{: ${e(skills.languages)}} \\\\
     \\textbf{Frameworks \\& Libraries}{: ${e(skills.frameworks)}} \\\\
     \\textbf{Tools}{: ${e(skills.tools)}}
    }}
 \\end{itemize}

%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
    \\resumeSubheading
      {University of Victoria}{Sep 2021 -- Dec 2025}
      {Bachelor of Science, Computer Science}{Victoria, BC}
  \\resumeSubHeadingListEnd

\\end{document}
`
}
